### ISSUE TITLE
Rotation 8 skips waves?

### ISSUE THREAD

**Issue by trent-wise** [runkev/fight-cave-helper#1]
When I click next on rotation 8 I am going 2 waves ahead instead of one, same with the back button. The spawn option buttons also seem to be duplicated.

**Comment by runkev** [comment]
> When I click next on rotation 8 I am going 2 waves ahead instead of one, same with the back button. The spawn option buttons also seem to be duplicated.

Can't seem to replicate that bug on my end. Can you detail your steps for me?

My steps for reference:
1. Wave 1: select "S".
2. Wave 2: select "NW" and "C".
3. Wave 3: Displays spawn that is the same for waves 7 and 8. Click "Next".
4. Wave 4: Select "SE" and "SW".
5. Wave 5: begins displaying Rotation 8 images, but (for me) increments correctly.

**Comment by trent-wise** [comment]
Looks like it may have been a runelite bug or something. After reinstalling the plugin it works!
Thanks for the prompt response though.
